name: Request Feature
description: Request a feature that might add to the project.
title: '[FEAT] <feature name>'
labels: [feat]
body:
  - type: markdown
    attributes:
      value: "## Before you continue, please search our open/closed issues to see if a similar feature has been requested."

  - type: checkboxes
    attributes:
      label: I have searched through the issues and didn't find my feature.
      options:
        - label: Confirm
          required: true

  - type: textarea
    id: feature-explaination
    attributes:
      label: Explain the feature and what it'll add.
    validations:
      required: true

  - type: textarea
    id: feature-example
    attributes:
      label: Propose an example for how the feature show work
      description: Give an example where this feature can be helpful and you can add images if needed.
    validations:
      required: true

  - type: textarea
    id: extra-information
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
